#!/bin/bash
#
# genconfig.sh - regenerate snapraid.conf from settings.ini
#
# settings.ini keys used:
#   PARITY_PATH=repurposed_parity    (the /mnt/<name> entry; /mnt/ is prepended below)
#   PARITY2_PATH=                    (optional second parity disk; empty = single parity)
#   DATA_DISKS=disk1,disk2,pool_disk1        (comma separated mount names under /mnt/)
#   EXCLUDES=*.tmp,/appdata/,/system/,/domains/,/isos/
#   CONTENT_DISKS=disk1,disk2,disk3          (which data disks also hold a content file, spread for safety)
#
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

PARITY_PATH=$(sre_get_setting "PARITY_PATH" "")
PARITY2_PATH=$(sre_get_setting "PARITY2_PATH" "")
DATA_DISKS=$(sre_get_setting "DATA_DISKS" "")
EXCLUDES=$(sre_get_setting "EXCLUDES" "*.tmp,*.bak,/appdata/,/system/,/domains/,/isos/,downloads/incomplete/")
CONTENT_DISKS=$(sre_get_setting "CONTENT_DISKS" "")

if [[ -z "$PARITY_PATH" || -z "$DATA_DISKS" ]]; then
    echo "ERROR: Parity path or data disks not configured yet. Finish Setup first." >&2
    exit 1
fi

# PARITY_PATH must be a mounted disk (array disk or pool). SnapRAID requires
# parity to be a regular file on a mounted filesystem - raw block devices
# (e.g. /dev/sdg) are NOT supported and fail with EINVAL during sync.
if [[ "$PARITY_PATH" == /dev/* ]]; then
    echo "ERROR: Raw devices aren't supported by SnapRAID. Format the disk and add it as a pool, then set the parity path to the pool name." >&2
    exit 1
fi
if ! mountpoint -q "/mnt/${PARITY_PATH}" 2>/dev/null; then
    echo "ERROR: Parity disk '${PARITY_PATH}' is not mounted. Start the pool/disk before syncing." >&2
    exit 1
fi

# Optional second parity disk. Same rules as the first (mounted, not a raw
# device) plus it must be a DIFFERENT disk - SnapRAID rejects parity and
# parity-2 on the same device.
if [[ -n "$PARITY2_PATH" ]]; then
    if [[ "$PARITY2_PATH" == /dev/* ]]; then
        echo "ERROR: Raw devices aren't supported by SnapRAID. Format the disk and add it as a pool, then set the second parity path to the pool name." >&2
        exit 1
    fi
    if [[ "$PARITY2_PATH" == "$PARITY_PATH" ]]; then
        echo "ERROR: The second parity disk must be different from the first parity disk." >&2
        exit 1
    fi
    if ! mountpoint -q "/mnt/${PARITY2_PATH}" 2>/dev/null; then
        echo "ERROR: Second parity disk '${PARITY2_PATH}' is not mounted. Start the pool/disk before syncing." >&2
        exit 1
    fi
fi

{
    echo "# Auto-generated by SnapUnraid - do not edit by hand."
    echo "# Edit via the plugin's Setup tab instead; this file is rewritten on every save."
    echo ""
    # PARITY_PATH is a mounted disk name ("disk1"/"ssd"/pool name) -> parity
    # is a file at /mnt/<name>/snapraid.parity. Raw devices are rejected above
    # (SnapRAID can't use them as parity).
    echo "parity /mnt/${PARITY_PATH}/snapraid.parity"
    if [[ -n "$PARITY2_PATH" ]]; then
        echo "parity-2 /mnt/${PARITY2_PATH}/snapraid.parity-2"
    fi
    echo ""

    # spread content files across the chosen content disks (falls back to first 3 data disks)
    IFS=',' read -ra CDISKS <<< "${CONTENT_DISKS:-$DATA_DISKS}"
    count=0
    for d in "${CDISKS[@]}"; do
        [[ -z "$d" ]] && continue
        echo "content /mnt/${d}/.snapraid/snapraid.content"
        count=$((count+1))
        [[ $count -ge 3 ]] && break
    done
    echo ""

    n=0
    IFS=',' read -ra DDISKS <<< "$DATA_DISKS"
    for d in "${DDISKS[@]}"; do
        [[ -z "$d" ]] && continue
        n=$((n+1))
        echo "data d${n} /mnt/${d}/"
    done
    echo ""

    IFS=',' read -ra EX <<< "$EXCLUDES"
    for e in "${EX[@]}"; do
        [[ -z "$e" ]] && continue
        echo "exclude ${e}"
    done
    echo ""
    echo "blocksize 256"
    echo "autosave 500"
} > "$SNAPRAID_CONF"

# make sure content directories exist
IFS=',' read -ra CDISKS <<< "${CONTENT_DISKS:-$DATA_DISKS}"
count=0
for d in "${CDISKS[@]}"; do
    [[ -z "$d" ]] && continue
    mkdir -p "/mnt/${d}/.snapraid"
    count=$((count+1))
    [[ $count -ge 3 ]] && break
done

echo "OK: wrote ${SNAPRAID_CONF}"
